fixed some loops

diff --git a/project1/install-packages b/project1/install-packages
--- a/project1/install-packages
+++ b/project1/install-packages
@@ -1,35 +1,29 @@
 #!/bin/bash
 
-# Define function to install packages from install-packages file
+# Returns 0 if the script is run with sudo or root, else prompt to rerun with root or sudo
+if [[ "$EUID" -ne 0 ]]; then
+  echo "Please run this script with sudo"
+  exit 1
+fi
 
-install-packages() {
+# Define the file containing the list of packages to install into a variable
+package_list="./packages"
 
-  # This will read all the lines in the install-packages file
+# Check if the install-packages file exists
+if [[ ! -f "$package_list" ]]; then
+  echo "Package list file '$package_list' not found!"
+  exit 1
+fi
 
-  while read -r package; do
+# Read and install each package from the install-packages file
+while read -r package; do
+  #looks for and installs kakoune and tmux in $package
+  echo "Installing $package"
+  # skips installation confirmation for pacman
+  pacman -S --noconfirm "$package"
+# < is used to specify the input file for the while loop
+done < $package_list
 
-    #This will install the packages and skip install confirmations for pacman 
 
-    if pacman -S --noconfirm "$package"; then
 
-      echo "$package installed successfully"
-
-    else
-
-      echo "$package failed to install"
-
-      #error indicator in case installation fails
-
-      exit 1
-
-    fi
-
-  # retrieves content from install-packages to be used as input in this while loop
-
-  done < ./install-packages  
-}
-
-# this invokes install-packages function to start the installation process
-
-install-packages
 
